image: python:3.13

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test:
  script:
    - python -m venv .venv
    - .\.venv\Scripts\Activate.ps1
    - pip install -r requirements.txt
    - ruff check .
    - pytest